package aplikasiinvestasi.model;
// Generated Nov 10, 2016 8:57:29 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MasterCredential generated by hbm2java
 */
@Entity
@Table(name="master_credential")
public class MasterCredential  implements java.io.Serializable {

     @Id
     @Column(name="privilege_code")
     private String privilegeCode;
     
     @Column(name="username")
     private String username;
     
     @Column(name="password")
     private String password;
     
     @Column(name="privilege")
     private String privilege;
     
     @Column(name="salt_key")
     private byte[] saltKey;
     
     @Column(name="status")
     private String status;

    public MasterCredential() {
    }

    public MasterCredential(String privilegeCode, String username, String password, String privilege, byte[] saltKey, String status) {
        this.privilegeCode = privilegeCode;
        this.username = username;
        this.password = password;
        this.privilege = privilege;
        this.saltKey = saltKey;
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getPrivilegeCode() {
        return this.privilegeCode;
    }
    
    public void setPrivilegeCode(String privilegeCode) {
        this.privilegeCode = privilegeCode;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }
    public byte[] getSaltKey() {
        return this.saltKey;
    }
    
    public void setSaltKey(byte[] saltKey) {
        this.saltKey = saltKey;
    }




}


