/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiinvestasi.view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Rizaldi Habibie
 */
public class DetailInvestView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetailInvestView
     */
    public DetailInvestView() {
        initComponents();
    }

    public JButton getEditButton() {
        return editButton;
    }

    public void setEditButton(JButton editButton) {
        this.editButton = editButton;
    }

    public JTextField getJenisField() {
        return jenisField;
    }

    public void setJenisField(JTextField jenisField) {
        this.jenisField = jenisField;
    }

    public JTextField getJumlahField() {
        return jumlahField;
    }

    public void setJumlahField(JTextField jumlahField) {
        this.jumlahField = jumlahField;
    }

    public JTextField getNoSuratIjinField() {
        return noSuratIjinField;
    }

    public void setNoSuratIjinField(JTextField noSuratIjinField) {
        this.noSuratIjinField = noSuratIjinField;
    }

    public JComboBox getPemohonField() {
        return pemohonField;
    }

    public void setPemohonField(JComboBox pemohonField) {
        this.pemohonField = pemohonField;
    }

    public JComboBox getPenanggungJawabField() {
        return penanggungJawabField;
    }

    public void setPenanggungJawabField(JComboBox penanggungJawabField) {
        this.penanggungJawabField = penanggungJawabField;
    }

    public JTextField getRencanaField() {
        return rencanaField;
    }

    public void setRencanaField(JTextField rencanaField) {
        this.rencanaField = rencanaField;
    }

    public JXDatePicker getTanggalField() {
        return tanggalField;
    }

    public void setTanggalField(JXDatePicker tanggalField) {
        this.tanggalField = tanggalField;
    }

    public JTable getViewTable() {
        return viewTable;
    }

    public void setViewTable(JTable viewTable) {
        this.viewTable = viewTable;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public void setButtonGroup2(ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    public JRadioButton getUnit1() {
        return unit1;
    }

    public void setUnit1(JRadioButton unit1) {
        this.unit1 = unit1;
    }

    public JRadioButton getUnit2() {
        return unit2;
    }

    public void setUnit2(JRadioButton unit2) {
        this.unit2 = unit2;
    }

    public JRadioButton getUnit3() {
        return unit3;
    }

    public void setUnit3(JRadioButton unit3) {
        this.unit3 = unit3;
    }

    public JRadioButton getUnit4() {
        return unit4;
    }

    public void setUnit4(JRadioButton unit4) {
        this.unit4 = unit4;
    }

    public JPanel getPanelData() {
        return panelData;
    }

    public void setPanelData(JPanel panelData) {
        this.panelData = panelData;
    }

    public JTextField getRealisasiBskkField() {
        return realisasiBskkField;
    }

    public void setRealisasiBskkField(JTextField realisasiBskkField) {
        this.realisasiBskkField = realisasiBskkField;
    }

    public JTextField getRealisasiLpbField() {
        return realisasiLpbField;
    }

    public void setRealisasiLpbField(JTextField realisasiLpbField) {
        this.realisasiLpbField = realisasiLpbField;
    }

    public JTextField getTotalRealisasiField() {
        return totalRealisasiField;
    }

    public void setTotalRealisasiField(JTextField totalRealisasiField) {
        this.totalRealisasiField = totalRealisasiField;
    }

    public JButton getExportButton() {
        return exportButton;
    }

    public void setExportButton(JButton exportButton) {
        this.exportButton = exportButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jenisField = new javax.swing.JTextField();
        jumlahField = new javax.swing.JTextField();
        noSuratIjinField = new javax.swing.JTextField();
        tanggalField = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        penanggungJawabField = new javax.swing.JComboBox();
        pemohonField = new javax.swing.JComboBox();
        rencanaField = new javax.swing.JTextField();
        realisasiLpbField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        unit1 = new javax.swing.JRadioButton();
        unit2 = new javax.swing.JRadioButton();
        unit3 = new javax.swing.JRadioButton();
        unit4 = new javax.swing.JRadioButton();
        realisasiBskkField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totalRealisasiField = new javax.swing.JTextField();
        exportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();

        panelData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nomor Proposal :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel2.setText("Nomor Surat Ijin");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel1.setText("Tanggal Ijin Investasi");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel3.setText("Jenis Investasi");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        jenisField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        jumlahField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        noSuratIjinField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        tanggalField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel7.setText("Pemohon");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel5.setText("Diajukan Oleh Departemen");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel6.setText("Rencana");

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel9.setText("Realisasi Dari LPB");

        penanggungJawabField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        penanggungJawabField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pemohonField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        pemohonField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rencanaField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        realisasiLpbField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        editButton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        editButton.setText("EDIT");

        buttonGroup1.add(unit1);
        unit1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        unit1.setText("Holo I");

        buttonGroup1.add(unit2);
        unit2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        unit2.setText("Holo II");

        buttonGroup2.add(unit3);
        unit3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        unit3.setText("Holo I");

        buttonGroup2.add(unit4);
        unit4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        unit4.setText("Holo II");

        realisasiBskkField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel10.setText("Realisasi Dari BSKK");

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel11.setText("Total Realisasi");

        totalRealisasiField.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N

        exportButton.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        exportButton.setText("Export To Excel");

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pemohonField, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noSuratIjinField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jenisField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rencanaField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(penanggungJawabField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(realisasiLpbField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDataLayout.createSequentialGroup()
                                .addComponent(unit3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unit4))
                            .addComponent(realisasiBskkField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDataLayout.createSequentialGroup()
                                .addComponent(totalRealisasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exportButton))))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(unit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unit2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noSuratIjinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit3)
                    .addComponent(unit4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penanggungJawabField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rencanaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realisasiLpbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unit1)
                    .addComponent(unit2)
                    .addComponent(realisasiBskkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pemohonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(totalRealisasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editButton)
                        .addComponent(exportButton)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(panelData, java.awt.BorderLayout.NORTH);

        viewTable.setFont(new java.awt.Font("Lucida Sans", 1, 11)); // NOI18N
        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(viewTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenisField;
    private javax.swing.JTextField jumlahField;
    private javax.swing.JTextField noSuratIjinField;
    private javax.swing.JPanel panelData;
    private javax.swing.JComboBox pemohonField;
    private javax.swing.JComboBox penanggungJawabField;
    private javax.swing.JTextField realisasiBskkField;
    private javax.swing.JTextField realisasiLpbField;
    private javax.swing.JTextField rencanaField;
    private org.jdesktop.swingx.JXDatePicker tanggalField;
    private javax.swing.JTextField totalRealisasiField;
    private javax.swing.JRadioButton unit1;
    private javax.swing.JRadioButton unit2;
    private javax.swing.JRadioButton unit3;
    private javax.swing.JRadioButton unit4;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
